config/routes.rb
Rails.application.routes.draw do
  # mount Attachinary::Engine => "/attachinary"
  # devise_for :users
  root to: 'pages#home'
  get '/en' => 'pages#home'
  get "/team" => 'pages#team'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # scope "/:locale" do
  scope "(:locale)", locale: /en|fr|da|ar|ja/ do
    resources :tasks do
      member do
        patch :change_status
      end
    end
    # patch "/tasks/:id/change_status" => tasks#change_status

  end
  # get "/tasks" => tasks#index
  # get "/tasks/:id" => tasks#show
  # get "/tasks/new" => tasks#new
  # post "/tasks" => tasks#create
  # get "/tasks/:id/edit" => tasks#edit
  # patch "/tasks/:id" => tasks#update
  # delete "/tasks/:id" => tasks#destroy

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :tasks, only: [ :index, :show ]
    end
  end

end

# member action apply to specfic and collections to all resources / tasks

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  def change_status!(status)
    self.status = status
    self.save
  end

  enum status: [:unplanned, :planned, :done, :deleted]
end


app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  # include Pundit

  # after_action :verify_authorized, except: :index
  # after_action :verify_policy_scoped, only: :index

  rescue_from StandardError,                with: :internal_server_error
  # rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end

  def internal_server_error(exception)
    if Rails.env.development?
      response = { type: exception.class.to_s, error: exception.message }
    else
      response = { error: "Internal Server Error" }
    end
    render json: response, status: :internal_server_error
  end
end

app/controllers/api/v1/tasks_controller.rb
class Api::V1::TasksController < Api::V1::BaseController
  before_action :set_task, only: [ :show ]

  def index
    @tasks = Task.all
  end

  def show
  end

  private

  def set_task
    @task = Task.find(params[:id])
    # authorize @task  # For Pundit
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!

  def home
    @today = Date.today
    @current_time = Time.now
  end

  def team
    # @members = ["Abrar Saad", "Amira Buz Khallouf", "Genki Takahashi", "Mohamad Alzoubi", "Finn Pedersen"]
    @members = ["Finn Pedersen"]
  end

  def join_us
    render plain: "Send us a mail"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy, :change_status]

  def index
    @unplanned_tasks = Task.where(status: 0).order(:urgency)
    @planned_tasks = Task.where(status: 1).order(:planned_date)
    @done_tasks = Task.where(status: 2).order(:removed_date)
    @deleted_tasks = Task.where(status: 3).order(:removed_date)

    @marvin_quote = Faker::HitchhikersGuideToTheGalaxy.marvin_quote
    # Faker::Hacker.say_something_smart
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def change_status
    @task.change_status!(params[:status])
    redirect_to tasks_path
  end

  def destroy
    @task.change_status!(:deleted)
    # @task.destroy
    redirect_to tasks_path
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:short_description,:long_description,:nature,:urgency,:duration,:attention_date,:deadline,:expiration_date,:planned_date,:starting_time,:removed_date,:status)
  end
end


app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Taskmanager02</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "background.jpg" %>');">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="#">Home</a></li>
            <li><%= link_to "Team", team_path %></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Languages <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Arabic", root_path(locale: "ar") %></li>
                <li><%= link_to "Danish", root_path(locale: "da") %></li>
                <li><%= link_to "English", root_path(locale: "en") %></li>
                <li><%= link_to "French", root_path(locale: "fr") %></li>
                <li><%= link_to "Japanese", root_path(locale: "ja") %></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  <div class="banner-content">
    <h1><%= t('welcome') %></h1>
    <p><%= t('tagline') %></p>
    <p><%= l(@current_time, format: :long) %></p>
    <%= link_to "My Tasks", tasks_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/pages/team.html.erb
<div class="container text-center">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <h1 class="text-center">Meet the team</h1>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="text-center">Name</th>
        </tr>
      </thead>
      <tbody>
        <% @members.each do |member| %>
          <tr>
            <td><%= member%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p><%= link_to "Home Page", root_path, class: "btn btn-primary" %></p>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <% if @task.status == "unplanned" %>
        <h1 class="text-center">Update Unplanned Task</h1>
        <%= simple_form_for @task do |f| %>
          <%= f.input :short_description, placeholder:"Short Description", label: "Short Description" %>
          <%= f.input :long_description, placeholder:"Long Description", label: "Long Description" %>
          <%= f.input :nature, placeholder:"Nature", label: "Nature" %>
          <%= f.input :urgency, placeholder:"Urgency", label: "Urgency" %>
          <%= f.input :duration, placeholder:"Duration", label: "Duration" %>
          <%= f.input :attention_date, as: :date_picker, placeholder: "Attention Date", label: "Attention Date" %>
          <%= f.input :deadline, as: :date_picker, placeholder: "Deadline", label: "Deadline" %>
          <%= f.input :expiration_date, as: :date_picker, placeholder: "Expiration Date", label: "Expiration Date"  %>
          <%= f.button :submit, "Update Task", class: "btn btn-primary" %>
          <%= link_to "Cancel", :back, class: "btn btn-warning" %>
        <% end %>
      <% elsif @task.status == "planned" %>
        <h1 class="text-center">Update Planned Task</h1>
        <%= simple_form_for @task do |f| %>
          <%= f.input :short_description, placeholder:"Short Description", label: "Short Description" %>
          <%= f.input :long_description, placeholder:"Long Description", label: "Long Description" %>
          <%= f.input :nature, placeholder:"Nature", label: "Nature" %>
          <%= f.input :urgency, placeholder:"Urgency", label: "Urgency" %>
          <%= f.input :duration, placeholder:"Duration", label: "Duration" %>
          <%= f.input :planned_date, as: :date_picker, placeholder:"Planned Date", label: "Planned Date" %>
          <%= f.input :starting_time, as: :time_picker, placeholder:"Starting Time", label: "Starting Time" %>
          <%= f.button :submit, "Update Task", class: "btn btn-primary" %>
          <%= link_to "Cancel", :back, class: "btn btn-warning" %>
        <% end %>
      <% elsif @task.status == "done" %>
        <h1 class="text-center">Update Done Task</h1>
        <%= simple_form_for @task do |f| %>
          <%= f.input :short_description, placeholder:"Short Description", label: "Short Description" %>
          <%= f.input :long_description, placeholder:"Long Description", label: "Long Description" %>
          <%= f.input :nature, placeholder:"Nature", label: "Nature" %>
          <%= f.input :urgency, placeholder:"Urgency", label: "Urgency" %>
          <%= f.input :duration, placeholder:"Duration", label: "Duration" %>
          <%= f.input :planned_date, as: :date_picker, placeholder:"Planned Date", label: "Planned Date" %>
          <%= f.input :starting_time, as: :time_picker, placeholder:"Starting Time", label: "Starting Time" %>
          <%= f.button :submit, "Update Task", class: "btn btn-primary" %>
          <%= link_to "Cancel", :back, class: "btn btn-warning" %>
        <% end %>
      <% else %>
        <h1 class="text-center">Update Deleted Task</h1>
        <%= simple_form_for @task do |f| %>
          <%= @task.short_description %>
          <%= @task.removed_date %>
          <%= @task.status %>
          <%= f.button :submit, "Update Task", class: "btn btn-primary" %>
          <%= link_to "Cancel", :back, class: "btn btn-warning" %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>




app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <!-- <div class="col-xs-12 col-sm-6 col-sm-offset-3"> -->
      <p></p>
      <p>
        <%= link_to "Home Page", root_path, class: "btn btn-primary" %>
        <%= link_to "Add Unplanned Task", new_task_path, class: "btn btn-primary" %>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#myModal">
          Marvin! Please, Help me.
        </button>
      </p>
      <h1 class="text-center">Planned Tasks</h1>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Short Description</th>
            <th>Long Description</th>
            <th>Nature</th>
            <th>Duration</th>
            <th>Planned Date</th>
            <th>Starting Time</th>
<!--
            <th>Urgency</th>
            <th>Attention Date</th>
            <th>Deadline</th>
            <th>Expiration Date</th>
            <th>Removed Date</th>
            <th>Status</th>
 -->
          </tr>
        </thead>
        <tbody>
          <% @planned_tasks.each do |task| %>
            <tr>
              <td><%= link_to task.short_description, task_path(task) %></td>
              <td><%= task.long_description %></td>
              <td><%= task.nature %></td>
              <td><%= task.duration %></td>
              <td><%= task.planned_date %></td>
              <% if task.starting_time? %>
                <td><%= task.starting_time.strftime("%H:%M") %></td>
              <% else %>
                <td></td>
              <% end %>

<!--
              <td><%= task.urgency %></td>
              <td><%= task.attention_date %></td>
              <td><%= task.deadline %></td>
              <td><%= task.expiration_date %></td>
              <td><%= task.removed_date %></td>
              <td><%= task.status %></td>
 -->
            </tr>
          <% end %>
        </tbody>
      </table>
      <hr />
      <h1 class="text-center">Unplanned Tasks</h1>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Short Description</th>
            <th>Nature</th>
            <th>Urgency</th>
            <th>Duration</th>
            <th>Attention Date</th>
            <th>Deadline</th>
<!--
            <th>Expiration Date</th>
            <th>Planned Date</th>
            <th>Starting Time</th>
            <th>Removed Date</th>
            <th>Status</th>
 -->
          </tr>
        </thead>
        <tbody>
          <% @unplanned_tasks.each do |task| %>
            <tr>
              <td><%= link_to task.short_description, task_path(task) %></td>
              <td><%= task.nature %></td>
              <td><%= task.urgency %></td>
              <td><%= task.duration %></td>
              <td><%= task.attention_date %></td>
              <td><%= task.deadline %></td>
<!--
              <td><%= task.expiration_date %></td>
              <td><%= task.planned_date %></td>
              <td><%= task.starting_time %></td>
              <td><%= task.removed_date %></td>
              <td><%= task.status %></td>
 -->
            </tr>
          <% end %>
        </tbody>
      </table>
      <hr />
      <h1 class="text-center">Done Tasks</h1>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Short Description</th>
            <th>Nature</th>
            <th>Urgency</th>
            <th>Duration</th>
            <th>Completed Date</th>
<!--
            <th>Planned Date</th>
            <th>Starting Time</th>
            <th>Attention Date</th>
            <th>Deadline</th>
            <th>Expiration Date</th>
            <th>Status</th>
 -->
          </tr>
        </thead>
        <tbody>
          <% @done_tasks.each do |task| %>
            <tr>
              <td><%= link_to task.short_description, task_path(task) %></td>
              <td><%= task.nature %></td>
              <td><%= task.urgency %></td>
              <td><%= task.duration %></td>
              <td><%= task.removed_date %></td>
<!--
              <td><%= task.planned_date %></td>
              <td><%= task.starting_time %></td>
              <td><%= task.attention_date %></td>
              <td><%= task.deadline %></td>
              <td><%= task.expiration_date %></td>
              <td><%= task.status %></td>
 -->
            </tr>
          <% end %>
        </tbody>
      </table>
      <hr />
      <h1 class="text-center">Deleted Tasks</h1>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Short Description</th>
            <th>Nature</th>
            <th>Urgency</th>
            <th>Duration</th>
            <th>Removed Date</th>
<!--
            <th>Planned Date</th>
            <th>Starting Time</th>
            <th>Attention Date</th>
            <th>Deadline</th>
            <th>Expiration Date</th>
            <th>Status</th>
 -->
          </tr>
        </thead>
        <tbody>
          <% @deleted_tasks.each do |task| %>
            <tr>
              <td><%= link_to task.short_description, task_path(task) %></td>
              <td><%= task.nature %></td>
              <td><%= task.urgency %></td>
              <td><%= task.duration %></td>
              <td><%= task.removed_date %></td>
<!--
              <td><%= task.planned_date %></td>
              <td><%= task.starting_time %></td>
              <td><%= task.attention_date %></td>
              <td><%= task.deadline %></td>
              <td><%= task.expiration_date %></td>
              <td><%= task.status %></td>
 -->
            </tr>
          <% end %>
        </tbody>
      </table>
    <!-- </div> -->
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="myModalLabel">Marvins says: </h2>
      </div>
      <div class="modal-body">
        <form action="#">
          <p class="text-center"><%= @marvin_quote %></p>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success btn-lg" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1 class="text-center">New Task</h1>
      <%= simple_form_for @task do |f| %>
        <%= f.input :short_description, placeholder:"Short Description", label: false %>
        <%= f.input :long_description, placeholder:"Long Description", label: false %>
        <%= f.input :nature, placeholder:"Nature", label: false %>
        <%= f.input :urgency, placeholder:"Urgency", label: false %>
        <%= f.input :duration, placeholder:"Duration", label: false %>

        <%= f.input :attention_date, as: :date_picker, placeholder: "Attention Date" %>
        <%= f.input :deadline, as: :date_picker, placeholder: "Deadline" %>
        <%= f.input :expiration_date, as: :date_picker, placeholder: "Expiration Date"  %>

        <%= f.button :submit, "Add Task", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<p class="text-center">
  <%= link_to "Tasks", tasks_path, class: "btn btn-primary"  %>
</p>


app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <% if @task.status == "unplanned" %>
        <h1 class="text-center">Unplanned Task</h1>
      <% elsif @task.status == "planned" %>
        <h1 class="text-center">Planned Task</h1>
      <% elsif @task.status == "done" %>
        <h1 class="text-center">Done Task</h1>
      <% elsif @task.status == "deleted" %>
        <h1 class="text-center">Deleted Task</h1>
      <% else %>
        <h1 class="text-center">Unknown Status Task</h1>
      <% end %>

      <p><strong>Short Description: </strong><%= @task.short_description %></p>
      <p><strong>Long Description: </strong><%= @task.long_description %></p>
      <p><strong>Nature: </strong><%= @task.nature %></p>
      <p><strong>Urgency: </strong><%= @task.urgency %></p>

      <% if @task.status == "unplanned" %>
        <p><strong>Duration: </strong><%= @task.duration %></p>
        <p><strong>Attention Date: </strong><%= @task.attention_date %></p>
        <p><strong>Deadline: </strong><%= @task.deadline %></p>
        <p><strong>Expiration Date: </strong><%= @task.expiration_date %></p>
      <% elsif @task.status == "planned" %>
        <p><strong>Planned Date: </strong><%= @task.planned_date %></p>
        <% if @task.starting_time? %>
          <p><strong>Starting Time: </strong><%= @task.starting_time.strftime("%H:%M") %></p>
        <% else %>
          <p><strong>Starting Time: </strong></p>
        <% end %>
        <p><strong>Duration: </strong><%= @task.duration + ' minutes' %></p>
      <% elsif @task.status == "done" %>
        <p><strong>Completed Date: </strong><%= @task.removed_date %></p>
                                            <!-- I need to fix this -->
      <% elsif @task.status == "deleted" %>
        <p><strong>Removed Date: </strong><%= @task.removed_date %></p>
      <% end %>

    </div>
  </div>
</div>
<p class="text-center">
  <% if @task.status != "deleted" %>
    <%= link_to "Edit", edit_task_path(@task), class: "btn btn-warning " %>
    <%= link_to "Move to bin", change_status_task_path(@task, status: :deleted), method: :patch, class: "btn btn-danger" %>
  <% end %>
  <%= link_to "Tasks", tasks_path, class: "btn btn-primary"  %>
</p>

<p class="text-center">
  <% if @task.status == "unplanned" %>
    <%= link_to "Move to planned", change_status_task_path(@task, status: :planned), method: :patch, class: "btn btn-primary" %>
    <%= link_to "Mark as done", change_status_task_path(@task, status: :done), method: :patch, class: "btn btn-primary" %>
  <% elsif @task.status == "planned" %>
    <%= link_to "Move to unplanned", change_status_task_path(@task, status: :unplanned), method: :patch, class: "btn btn-primary" %>
    <%= link_to "Mark as done", change_status_task_path(@task, status: :done), method: :patch, class: "btn btn-primary" %>
  <% elsif @task.status == "done" %>
    <%= link_to "Move to unplanned", change_status_task_path(@task, status: :unplanned), method: :patch, class: "btn btn-primary" %>
  <% elsif @task.status == "deleted" %>
    <%= link_to "Move to unplanned", change_status_task_path(@task, status: :unplanned), method: :patch, class: "btn btn-primary" %>
    <%= link_to "Delete Permanently", task_path(@task), method: :delete, class: "btn btn-danger" %>
  <% end %>

</p>


